name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make exercise 1
      run: g++ Lab5/exercise1.cpp && ./a.out
    - name: make exercise 2
      run: g++ Lab5/exercise2.cpp && ./a.out
    - name: make exercise 3
      run: g++ Lab5/exercise3.cpp && ./a.out

